### ISSUE TITLE
Error recovery

### ISSUE THREAD

**Issue by dguerizec** [Dridi/cashpack#4]
Hello @Dridi,

In the context of HTTP/2 passive monitoring, I'm looking for an HPACK lib that would be able to handle error recoveries from missing indexes in the dynamic table.
Missing indexes can occur when the capture process misses or drops some packets.

I tried to use nghttp2 but the coupling between HPACK decoding and the dynamic table management is too tight.
I think this is feasible with cashpack, and I actually already have a (kinda quick'n'dirty) proof of concept.

My question is, will you be willing to take PR's to handle error recovery on HPACK decoding ?

If yes, I'll do my very best to write the code in the same spirit as yours. My PoC is already event-based, and it's only about 5 LoCs in the cashpack library.

Best regards
David

**Comment by Dridi** [comment]
Hello David,

> My question is, will you be willing to take PR's to handle error recovery on HPACK decoding ?

Sure, I'll close this issue and wait for a PR to resume the discussion there. I'm a little bit skeptical about what we can do in terms of recovery (for h2 that would equate to a connection error, not merely dropping a stream) but it will be easier to review actual code rather than making blind assumptions.

> If yes, I'll do my very best to write the code in the same spirit as yours.

Don't worry about code style, I can fix that myself if that really becomes an issue. I'll be stricter on test coverage but again, I can help or write the test cases myself. Especially since cashpack's test framework is home-brew.

> My PoC is already event-based, and it's only about 5 LoCs in the cashpack library.

Also, bear with me, HPACK is not a moving target so little happened with cashpack in the last couple years (even though I have a few ideas in the back of my mind). I might need some time to rebuild a mental model of the library and RFCs, even for 5 LoCs :)

Finally, I'd be happy to learn more about your h2 passive monitoring project if that is OK. Feel free to send me a direct email.

Best Regards,
Dridi
